[project]
name = "cs-go-match-predictor-04-evaluate-model"
version = "0.1.0"
requires-python = ">= 3.12"

dependencies = [
    "pandas==3.0.2",
    "tensorflow==2.21.0",
    "scikit-learn==1.8.0",
    "joblib==1.5.3",
    "numpy==2.4.4",
    "requests==2.33.1", # CVE-2026-25645
    "pygments==2.20.0" # CVE-2026-4539
]

[project.optional-dependencies]
dev = ["ipykernel", "mypy", "ruff", "ipywidgets", "pandas-stubs"]
